title:              ycdfwzy's Blog
tagline:            on GitHub Pages
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://ycdfwzy.github.io

author:
  name:             ycdfwzy
  url:              https://twitter.com/ycdfwzy
  email:            ycdfwzy@outlook.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
